version: '3'
services:
  snapserver:
    build:
      context: ../.
      dockerfile: DockerfileServerX86
      args:
        SNAPCASTVERSION: 0.11.1

  snapclient:
    build:
      context: ../.
      dockerfile: DockerfileClientX86
      args:
        SNAPCASTVERSION: 0.11.1
    links:
     - snapserver:snapserverhost
    devices:
     - "/dev/snd/:/dev/snd/"
    command: "-h snapserverhost"